name: christhesoul.com
title: Chris Waters // @christhesoul
layout: default
plugins:
  - jemoji
defaults:
  -
    scopes:
      path: ""
    values:
      bg-color: 'lightest-blue'
      layout: 'default'
